apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: myjobplanner-api
      context: ./
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s/local
  kubeContext: minikube
