apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
    - image: myjobplanner-api-image
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        dependencies:
          paths:
          - src/*.ts
deploy:
  logs:
    jsonParse:
      fields: ["res"]
  kustomize:
    paths:
    - k8s/local
  kubeContext: knative
# portForward:
# - resourceType: deployment
#   resourceName: myjobplanner-api-deployment
#   port: 3000
#   address: 0.0.0.0
#   localPort: 3000