apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: myjobplanner-api
      context: ./
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
  kubeContext: minikube
