apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
    - image: myjobplanner-api
      context: ./
      docker:
        dockerfile: Dockerfile
deploy:
  logs:
    jsonParse:
      fields: ["res"]
  kustomize:
    paths:
    - k8s/local
  kubeContext: minikube
