http://localhost:3000/v1/businesses
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJrWkVOMFl3TkRGRU5FWTFRa0pCUVRGRVJVVTBOek0xT0RsRE9VSXpNVUV3UWpNNU9VSkJSUSJ9.eyJodHRwczovL2FwaS5teWpvYnBsYW5uZXIuY29tL3JvbGVzIjpbXSwiaXNzIjoiaHR0cHM6Ly9teWpvYnBsYW5uZXIuZXUuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE1NzQ1Njc0ODA1ODY2OTYyMjkzIiwiYXVkIjpbImh0dHBzOi8vYXBpLm15am9icGxhbm5lci5jb20iLCJodHRwczovL215am9icGxhbm5lci5ldS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjM1NjMwNjUwLCJleHAiOjE2MzU2Mzc4NTAsImF6cCI6IjA1aXhScFVSaGpab2RQajVsRENnN1hJRDlXVm1INWxTIiwic2NvcGUiOiJvcGVuaWQgcmVhZDpidXNpbmVzcyJ9.ylfkwf7yR4hFuVKXzJ81miT3aNjIsIVh96PrFBEVvu5UT0IH_qd46OrO5PQdj_GYzXhZyYApCuy30eWOV2tm6R3HGW4s8TENxnbf6cUqxJNLfterIOlH08U4hmxGzMZlQ_cB2SXVlRKMgyjYgk7G6J10VrcJLz3qgHomNyYLY1dkB1X9l6wplo5guayFKPt85Ou67g5CMrOic2MUrDPbfNYH9DH27pl8jkLHXREcS4ohNDngrG5YXv_ult4-jscD_yXySQee1MAeuciipiovz73yvPrZlbxs_D6kMcOCP-0yPZtYvzEe2pWW8xzF13zOvlqwU6UrdZgHYnmEA-aQgg
