/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v5.0.0), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2021 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 103 }

  /* === schema: public === */

  /* --- enums --- */


  /* --- tables --- */

  /**
   * **businesses**
   * - Table in database
   */
  export namespace businesses {
    export type Table = 'businesses';
    export interface Selectable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id: number;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone: string;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code: string;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number: string | null;
      /**
      * **businesses.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **businesses.created**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      created: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id: number;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone: string;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code: string;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number: string | null;
      /**
      * **businesses.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string;
      /**
      * **businesses.created**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      created: db.TimestampString | null;
    }
    export interface Whereable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.created**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **businesses.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **businesses.created**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **businesses.email**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      email?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **businesses.created**
      * - `timestamp` in database
      * - Nullable, default: `now()`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'businesses_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* === cross-table types === */

  export type Table = businesses.Table;
  export type Selectable = businesses.Selectable;
  export type JSONSelectable = businesses.JSONSelectable;
  export type Whereable = businesses.Whereable;
  export type Insertable = businesses.Insertable;
  export type Updatable = businesses.Updatable;
  export type UniqueIndex = businesses.UniqueIndex;
  export type Column = businesses.Column;
  export type AllBaseTables = [businesses.Table];
  export type AllForeignTables = [];
  export type AllViews = [];
  export type AllMaterializedViews = [];
  export type AllTablesAndViews = [businesses.Table];


  export type SelectableForTable<T extends Table> = {
    businesses: businesses.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    businesses: businesses.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    businesses: businesses.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    businesses: businesses.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    businesses: businesses.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    businesses: businesses.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    businesses: businesses.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    businesses: businesses.SQL;
  }[T];

}
