/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v5.0.0), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2021 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 103 }

  /* === schema: public === */

  /* --- enums --- */

  export type employee_role = 'admin' | 'worker';
  export namespace every {
    export type employee_role = ['admin', 'worker'];
  }
  export type invoice_job_choices = 'closed' | 'monthly' | 'never' | 'visit';
  export namespace every {
    export type invoice_job_choices = ['closed', 'monthly', 'never', 'visit'];
  }

  /* --- tables --- */

  /**
   * **businesses**
   * - Table in database
   */
  export namespace businesses {
    export type Table = 'businesses';
    export interface Selectable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id: number;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone: string;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code: string;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number: string | null;
      /**
      * **businesses.vat**
      * - `int4` in database
      * - `NOT NULL`, default: `25`
      */
      vat: number;
      /**
      * **businesses.visit_reminders**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      visit_reminders: boolean;
      /**
      * **businesses.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created: Date;
    }
    export interface JSONSelectable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id: number;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone: string;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code: string;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number: string | null;
      /**
      * **businesses.vat**
      * - `int4` in database
      * - `NOT NULL`, default: `25`
      */
      vat: number;
      /**
      * **businesses.visit_reminders**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      visit_reminders: boolean;
      /**
      * **businesses.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created: db.TimestampTzString;
    }
    export interface Whereable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.vat**
      * - `int4` in database
      * - `NOT NULL`, default: `25`
      */
      vat?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.visit_reminders**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      visit_reminders?: boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.SQLFragment | db.ParentColumn>;
      /**
      * **businesses.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **businesses.vat**
      * - `int4` in database
      * - `NOT NULL`, default: `25`
      */
      vat?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **businesses.visit_reminders**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      visit_reminders?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment;
      /**
      * **businesses.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **businesses.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('businesses_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **businesses.name**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **businesses.timezone**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      timezone?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **businesses.country_code**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      country_code?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **businesses.vat_number**
      * - `varchar` in database
      * - Nullable, no default
      */
      vat_number?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **businesses.vat**
      * - `int4` in database
      * - `NOT NULL`, default: `25`
      */
      vat?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **businesses.visit_reminders**
      * - `bool` in database
      * - `NOT NULL`, default: `false`
      */
      visit_reminders?: boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, boolean | db.Parameter<boolean> | db.DefaultType | db.SQLFragment>;
      /**
      * **businesses.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'businesses_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **employees**
   * - Table in database
   */
  export namespace employees {
    export type Table = 'employees';
    export interface Selectable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id: number;
      /**
      * **employees.user_id**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      user_id: string;
      /**
      * **employees.business_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      business_id: number;
      /**
      * **employees.role**
      * - `employee_role` in database
      * - `NOT NULL`, no default
      */
      role: employee_role;
      /**
      * **employees.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created: Date;
    }
    export interface JSONSelectable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id: number;
      /**
      * **employees.user_id**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      user_id: string;
      /**
      * **employees.business_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      business_id: number;
      /**
      * **employees.role**
      * - `employee_role` in database
      * - `NOT NULL`, no default
      */
      role: employee_role;
      /**
      * **employees.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created: db.TimestampTzString;
    }
    export interface Whereable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **employees.user_id**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      user_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **employees.business_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      business_id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **employees.role**
      * - `employee_role` in database
      * - `NOT NULL`, no default
      */
      role?: employee_role | db.Parameter<employee_role> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, employee_role | db.Parameter<employee_role> | db.SQLFragment | db.ParentColumn>;
      /**
      * **employees.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **employees.user_id**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      user_id: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **employees.business_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      business_id: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **employees.role**
      * - `employee_role` in database
      * - `NOT NULL`, no default
      */
      role: employee_role | db.Parameter<employee_role> | db.SQLFragment;
      /**
      * **employees.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **employees.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('employees_id_seq'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **employees.user_id**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      user_id?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **employees.business_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      business_id?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **employees.role**
      * - `employee_role` in database
      * - `NOT NULL`, no default
      */
      role?: employee_role | db.Parameter<employee_role> | db.SQLFragment | db.SQLFragment<any, employee_role | db.Parameter<employee_role> | db.SQLFragment>;
      /**
      * **employees.created**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
      created?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'employees_pkey' | 'employees_user_id_business_id_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* === cross-table types === */

  export type Table = businesses.Table | employees.Table;
  export type Selectable = businesses.Selectable | employees.Selectable;
  export type JSONSelectable = businesses.JSONSelectable | employees.JSONSelectable;
  export type Whereable = businesses.Whereable | employees.Whereable;
  export type Insertable = businesses.Insertable | employees.Insertable;
  export type Updatable = businesses.Updatable | employees.Updatable;
  export type UniqueIndex = businesses.UniqueIndex | employees.UniqueIndex;
  export type Column = businesses.Column | employees.Column;
  export type AllBaseTables = [businesses.Table, employees.Table];
  export type AllForeignTables = [];
  export type AllViews = [];
  export type AllMaterializedViews = [];
  export type AllTablesAndViews = [businesses.Table, employees.Table];


  export type SelectableForTable<T extends Table> = {
    businesses: businesses.Selectable;
    employees: employees.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    businesses: businesses.JSONSelectable;
    employees: employees.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    businesses: businesses.Whereable;
    employees: employees.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    businesses: businesses.Insertable;
    employees: employees.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    businesses: businesses.Updatable;
    employees: employees.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    businesses: businesses.UniqueIndex;
    employees: employees.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    businesses: businesses.Column;
    employees: employees.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    businesses: businesses.SQL;
    employees: employees.SQL;
  }[T];

}
