name: myJobPlanner Api Integration Tests
on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container: node:16.16.0-bullseye

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: myjobplanner
          POSTGRES_PASSWORD: myjobplanner
          POSTGRES_DB: myjobplanner
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npx graphile-migrate migrate
        env:
          DATABASE_URL: postgres://myjobplanner:myjobplanner@postgres/myjobplanner

      - name: Run integration tests
        run: npm run test-integration
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: myjobplanner
          POSTGRES_PASSWORD: myjobplanner
          POSTGRES_DB: myjobplanner
